# Generated by Django 4.2.20 on 2025-11-23 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email notifications (will be used in Phase 2)')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('email_application_updates', models.BooleanField(default=True)),
                ('email_ranking_updates', models.BooleanField(default=True)),
                ('email_edit_reports', models.BooleanField(default=True)),
                ('email_achievements', models.BooleanField(default=True)),
                ('in_app_application_updates', models.BooleanField(default=True)),
                ('in_app_ranking_updates', models.BooleanField(default=True)),
                ('in_app_edit_reports', models.BooleanField(default=True)),
                ('in_app_achievements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('application_approved', 'Application Approved'), ('application_disapproved', 'Application Disapproved'), ('ranking_updated', 'Ranking Updated'), ('edit_of_week_daily', 'Edit of the Week Daily Report'), ('title_unlocked', 'Title Unlocked'), ('edit_verified', 'Edit Verified'), ('edit_rejected', 'Edit Rejected')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx')],
            },
        ),
    ]
