# Generated by Django 4.2.20 on 2025-11-04 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_link', models.URLField(help_text='YouTube or TikTok channel URL', max_length=500)),
                ('channel_type', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                ('channel_name', models.CharField(blank=True, help_text='Fetched from channel', max_length=200)),
                ('channel_thumbnail', models.URLField(blank=True, help_text='Channel thumbnail URL', max_length=500)),
                ('follower_count', models.BigIntegerField(default=0, help_text='Follower/subscriber count')),
                ('editing_area', models.CharField(choices=[('transformers', 'Transformers'), ('dc', 'DC'), ('marvel', 'Marvel'), ('anime', 'Anime'), ('all', 'All'), ('others', 'Others')], max_length=50)),
                ('editing_area_other', models.CharField(blank=True, help_text="If 'others' is selected", max_length=200)),
                ('channel_verified', models.BooleanField(default=False, help_text='User confirmed this is their channel')),
                ('data_consent', models.BooleanField(default=False, help_text='User consented to data usage')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('rank_position', models.IntegerField(blank=True, help_text='Position in ranking table', null=True)),
                ('removal_requested', models.BooleanField(default=False)),
                ('removal_requested_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-follower_count', 'applied_date'],
                'unique_together': {('user', 'channel_link')},
            },
        ),
    ]
