# Generated by Django 4.2.20 on 2025-11-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorapplication',
            name='channel_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of the channel page to verify ownership', null=True, upload_to='editinghub_screenshots/'),
        ),
    ]
