from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0002_editorapplication_channel_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorapplication',
            name='editing_tool',
            field=models.CharField(
                choices=[
                    ('premiere', 'Adobe Premiere Pro'),
                    ('after_effects', 'Adobe After Effects'),
                    ('davinci', 'DaVinci Resolve'),
                    ('final_cut', 'Final Cut Pro'),
                    ('capcut', 'CapCut'),
                    ('sony_vegas', 'Sony Vegas Pro'),
                    ('other', 'Other')
                ],
                default='other',
                max_length=50,
            ),
        ),
    ]
# Generated by Django 4.2.20 on 2025-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0002_editorapplication_channel_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorapplication',
            name='editing_tool',
            field=models.CharField(choices=[('premiere', 'Adobe Premiere Pro'), ('after_effects', 'Adobe After Effects'), ('davinci', 'DaVinci Resolve'), ('final_cut', 'Final Cut Pro'), ('capcut', 'CapCut'), ('sony_vegas', 'Sony Vegas Pro'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
