# Generated by Django 4.2.20 on 2025-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0005_rank_trend_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorapplication',
            name='editing_tool',
            field=models.CharField(choices=[('after_effects', 'After Effects'), ('alight_motion', 'Alight Motion'), ('capcut', 'CapCut'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
