# Generated by Django 4.2.20 on 2025-11-06 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edithub', '0006_alter_editorapplication_editing_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_link', models.URLField(help_text='YouTube or TikTok channel URL', max_length=500)),
                ('channel_type', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('channel_thumbnail', models.URLField(blank=True, max_length=500)),
                ('channel_screenshot', models.ImageField(blank=True, help_text='Screenshot of the channel page to verify ownership', null=True, upload_to='edit_submissions/verification/')),
                ('channel_verified', models.BooleanField(default=False)),
                ('video_url', models.URLField(help_text='YouTube Shorts or TikTok video URL', max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('upvote_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured in top 3 of the week')),
                ('week_rank', models.IntegerField(blank=True, help_text='Rank in Edit of the Week (1-3)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvote_count', '-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='EditUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edit_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='edithub.editsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('user', 'edit_submission')},
            },
        ),
        migrations.CreateModel(
            name='EditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('explicit', 'Explicit Content'), ('spam', 'Spam'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edit_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='edithub.editsubmission')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('user', 'edit_submission')},
            },
        ),
    ]
