# Generated by Django 4.2.20 on 2025-11-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0007_editsubmission_editupvote_editreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsubmission',
            name='channel_screenshot',
        ),
        migrations.RemoveField(
            model_name='editsubmission',
            name='channel_verified',
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='approved_application',
            field=models.ForeignKey(blank=True, help_text="The approved EditorApplication that verifies this user's channel", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_submissions', to='edithub.editorapplication'),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='channel_link',
            field=models.URLField(help_text='YouTube or TikTok channel URL (from approved application)', max_length=500),
        ),
    ]
