# Generated by Django 4.2.20 on 2025-11-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0008_remove_editsubmission_channel_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editsubmission',
            options={'ordering': ['-calculated_points', '-submitted_date']},
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='calculated_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total calculated points for ranking', max_digits=10),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='comments',
            field=models.BigIntegerField(default=0, help_text='Video comments from platform'),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='last_points_calculation',
            field=models.DateTimeField(blank=True, help_text='Last time points were calculated', null=True),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='likes',
            field=models.BigIntegerField(default=0, help_text='Video likes from platform'),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='subscriber_count',
            field=models.BigIntegerField(default=0, help_text='Subscriber/follower count for normalization'),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='views',
            field=models.BigIntegerField(default=0, help_text='Video views from platform'),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='weeks_participated',
            field=models.IntegerField(default=1, help_text='Number of consecutive weeks user has submitted edits'),
        ),
    ]
