# Generated by Django 4.2.20 on 2025-11-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0009_alter_editsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsubmission',
            name='direct_video_url',
            field=models.URLField(blank=True, help_text='Direct video file URL (extracted via web scraping for TikTok, used for clean HTML5 video player)', max_length=1000, null=True),
        ),
    ]
