# Generated by Django 4.2.20 on 2025-11-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0011_editsubmission_scheduled_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament of Editors', help_text='Tournament name', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active tournament should exist')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('participant_1', models.ForeignKey(blank=True, help_text='Semi-Final 1 - First participant', limit_choices_to={'removal_requested': False, 'status': 'accepted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participant_1', to='edithub.editorapplication')),
                ('participant_2', models.ForeignKey(blank=True, help_text='Semi-Final 1 - Second participant', limit_choices_to={'removal_requested': False, 'status': 'accepted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participant_2', to='edithub.editorapplication')),
                ('participant_3', models.ForeignKey(blank=True, help_text='Semi-Final 2 - First participant', limit_choices_to={'removal_requested': False, 'status': 'accepted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participant_3', to='edithub.editorapplication')),
                ('participant_4', models.ForeignKey(blank=True, help_text='Semi-Final 2 - Second participant', limit_choices_to={'removal_requested': False, 'status': 'accepted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participant_4', to='edithub.editorapplication')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['-is_active', '-created_date'],
            },
        ),
    ]
