# Generated by Django 4.2.20 on 2025-11-21 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edithub', '0012_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='The winning video URL (prevents resubmission)', max_length=500)),
                ('week_start', models.DateField(help_text='Monday of the competition week')),
                ('week_rank', models.IntegerField(help_text='Rank in Edit of the Week (1, 2, or 3)')),
                ('channel_type', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok')], help_text='Platform type (YouTube or TikTok)', max_length=20)),
                ('channel_name', models.CharField(blank=True, help_text='Channel name at time of win', max_length=200)),
                ('title', models.CharField(blank=True, help_text='Edit title at time of win', max_length=200)),
                ('calculated_points', models.DecimalField(decimal_places=2, default=0.0, help_text='Points at time of win', max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edit_submission', models.OneToOneField(help_text='The EditSubmission that won', on_delete=django.db.models.deletion.CASCADE, related_name='week_winner_record', to='edithub.editsubmission')),
                ('user', models.ForeignKey(help_text='The user who won', on_delete=django.db.models.deletion.CASCADE, related_name='week_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Week Winner',
                'verbose_name_plural': 'Week Winners',
                'ordering': ['-week_start', 'week_rank'],
                'indexes': [models.Index(fields=['video_url'], name='edithub_wee_video_u_5ee9ec_idx'), models.Index(fields=['week_start', 'week_rank'], name='edithub_wee_week_st_5a2661_idx'), models.Index(fields=['user'], name='edithub_wee_user_id_cfbfca_idx')],
                'unique_together': {('video_url', 'week_start')},
            },
        ),
    ]
