# Generated by Django 4.2.20 on 2025-11-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0013_add_week_winner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finalist_1',
            field=models.ForeignKey(blank=True, help_text='Finalist 1 - Winner from Semi-Final 1 (left side)', limit_choices_to={'removal_requested': False, 'status': 'accepted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_finalist_1', to='edithub.editorapplication'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='finalist_2',
            field=models.ForeignKey(blank=True, help_text='Finalist 2 - Winner from Semi-Final 2 (right side)', limit_choices_to={'removal_requested': False, 'status': 'accepted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_finalist_2', to='edithub.editorapplication'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='finals_active',
            field=models.BooleanField(default=False, help_text='Finals phase is active'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='semi_finals_active',
            field=models.BooleanField(default=True, help_text='Semi-finals phase is active'),
        ),
    ]
