# Generated by Django 4.2.20 on 2025-11-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edithub', '0014_add_tournament_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finalist_1_edit_link',
            field=models.URLField(blank=True, help_text='Edit link for finalist 1 (YouTube or TikTok URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='finalist_2_edit_link',
            field=models.URLField(blank=True, help_text='Edit link for finalist 2 (YouTube or TikTok URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participant_1_edit_link',
            field=models.URLField(blank=True, help_text='Edit link for participant 1 (YouTube or TikTok URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participant_2_edit_link',
            field=models.URLField(blank=True, help_text='Edit link for participant 2 (YouTube or TikTok URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participant_3_edit_link',
            field=models.URLField(blank=True, help_text='Edit link for participant 3 (YouTube or TikTok URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participant_4_edit_link',
            field=models.URLField(blank=True, help_text='Edit link for participant 4 (YouTube or TikTok URL)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TournamentMatchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('semi_final_1', 'Semi-Final 1'), ('semi_final_2', 'Semi-Final 2'), ('final', 'Final')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='edithub.tournament')),
                ('voted_for', models.ForeignKey(help_text='The participant that received this vote', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_votes_received', to='edithub.editorapplication')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament Match Vote',
                'verbose_name_plural': 'Tournament Match Votes',
                'ordering': ['-created_date'],
                'unique_together': {('tournament', 'match_type', 'voter')},
            },
        ),
    ]
