# Generated by Django 4.2.20 on 2025-11-22 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0015_add_tournament_edit_links_and_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Title name (e.g., 'Ultimate Editing Master')", max_length=100, unique=True)),
                ('rarity', models.CharField(choices=[('ordinary', 'Ordinary'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='ordinary', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the title')),
                ('cost_coins', models.IntegerField(default=0, help_text='Cost in coins to unlock (0 = free/unlocked by default)')),
                ('is_default', models.BooleanField(default=False, help_text='Default title for new users')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this title is available')),
                ('unlock_requirement', models.CharField(blank=True, help_text="Requirement to unlock (e.g., 'Win 10 Edit of the Week', 'Reach 1000 followers')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rarity', 'cost_coins', 'name'],
            },
        ),
        migrations.AddField(
            model_name='editorapplication',
            name='selected_title',
            field=models.ForeignKey(blank=True, help_text='Selected custom editor title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='edithub.editortitle'),
        ),
    ]
