# Generated by Django 4.2.20 on 2025-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0016_editortitle_editorapplication_selected_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editortitle',
            options={'ordering': ['category', 'rarity', 'cost_coins', 'name']},
        ),
        migrations.AddField(
            model_name='editortitle',
            name='category',
            field=models.CharField(choices=[('reel', 'Reel Title'), ('comment', 'Comment Title'), ('general', 'General Title')], default='general', help_text='Category of the title (reel, comment, or general)', max_length=20),
        ),
    ]
