# Generated by Django 4.2.20 on 2025-11-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edithub', '0017_alter_editortitle_options_editortitle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='editortitle',
            name='achievement_group',
            field=models.CharField(blank=True, help_text="Group name for related achievement tiers (e.g., 'weekly_wins', 'point_master')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editortitle',
            name='achievement_threshold',
            field=models.IntegerField(default=0, help_text='Threshold value for the achievement (e.g., 5 wins, 1000 points)'),
        ),
        migrations.AddField(
            model_name='editortitle',
            name='achievement_type',
            field=models.CharField(blank=True, choices=[('edit_of_week_wins', 'Edit of the Week Wins'), ('total_points', 'Total Points'), ('points_per_edit', 'Points Per Edit'), ('consecutive_weeks', 'Consecutive Weeks Participated'), ('total_submissions', 'Total Submissions'), ('rank_1_wins', 'Rank #1 Wins'), ('rank_2_wins', 'Rank #2 Wins'), ('rank_3_wins', 'Rank #3 Wins')], help_text="Type of achievement required to unlock (only used if unlock_method is 'achievement' or 'both')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='editortitle',
            name='tier_level',
            field=models.IntegerField(default=1, help_text='Tier level for this achievement (1, 2, 3, etc.) - helps organize multiple tiers'),
        ),
        migrations.AddField(
            model_name='editortitle',
            name='unlock_method',
            field=models.CharField(choices=[('coins', 'Coins Only'), ('achievement', 'Achievement Only'), ('both', 'Coins or Achievement')], default='coins', help_text='How this title can be unlocked', max_length=20),
        ),
        migrations.CreateModel(
            name='UserTitleUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_method', models.CharField(choices=[('coins', 'Coins'), ('achievement', 'Achievement')], default='achievement', help_text='How this title was unlocked', max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='edithub.editortitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Title Unlock',
                'verbose_name_plural': 'User Title Unlocks',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
