# Generated by Django 4.2.20 on 2025-11-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0018_editortitle_achievement_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editortitle',
            name='achievement_type',
            field=models.CharField(blank=True, choices=[('rank_1_wins', 'Number of Edit of the Week Wins (First Place)'), ('total_points', 'Total Points (Overall)'), ('points_per_edit', 'Points Per Single Edit')], help_text="Type of achievement required to unlock (only used if unlock_method is 'achievement' or 'both')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='editortitle',
            name='rarity',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='ordinary', max_length=20),
        ),
    ]
