# Generated by Django 4.2.20 on 2025-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0019_add_rare_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editortitle',
            name='achievement_type',
            field=models.CharField(blank=True, choices=[('rank_1_wins', 'Number of Edit of the Week Wins (First Place)'), ('rank_2_wins', 'Number of Edit of the Week Wins (Second Place)'), ('rank_3_wins', 'Number of Edit of the Week Wins (Third Place)'), ('total_points', 'Total Points (Overall)'), ('points_per_edit', 'Points Per Single Edit')], help_text="Type of achievement required to unlock (only used if unlock_method is 'achievement' or 'both')", max_length=50, null=True),
        ),
    ]
