# Generated by Django 4.2.20 on 2025-11-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0022_alter_editortitle_achievement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertitleunlock',
            name='unlock_method',
            field=models.CharField(choices=[('coins', 'Coins'), ('achievement', 'Achievement'), ('manual', 'Manual (Admin)')], default='achievement', help_text='How this title was unlocked', max_length=20),
        ),
    ]
