# Generated by Django 4.2.20 on 2025-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0023_add_manual_unlock_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editortitle',
            name='unlock_method',
            field=models.CharField(choices=[('coins', 'Coins Only'), ('achievement', 'Achievement Only'), ('both', 'Coins or Achievement'), ('manual', 'Manual (Admin Only)')], default='coins', help_text='How this title can be unlocked', max_length=20),
        ),
    ]
