# Generated by Django 4.2.20 on 2025-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='onetimepassword',
            unique_together={('user', 'code')},
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['user', 'code'], name='accounts_on_user_id_60312d_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['created_at'], name='accounts_on_created_ea50ad_idx'),
        ),
    ]
