# Generated by Django 4.2.20 on 2025-11-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_channel_source',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok')], help_text='Which channel to use for profile display (if user has both YouTube and TikTok)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_display_mode',
            field=models.CharField(choices=[('account', 'Account Profile'), ('channel', 'Channel Profile')], default='account', help_text='Display account profile or channel profile', max_length=20),
        ),
    ]
