# Generated by Django 4.2.20 on 2025-11-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edithub', '0019_add_rare_rarity'),
        ('accounts', '0013_add_profile_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_title',
            field=models.ForeignKey(blank=True, help_text='Selected editor title that applies to all platforms (YouTube and TikTok)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='edithub.editortitle'),
        ),
    ]
