# Generated by Django 4.2.20 on 2025-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_unified_editor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mix_rank_position',
            field=models.IntegerField(blank=True, help_text='Position in mix ranking table (combines YouTube + TikTok followers)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mix_rank_position_last_week',
            field=models.IntegerField(blank=True, help_text="Last week's mix rank position for trend arrows", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mix_rank_snapshot_at',
            field=models.DateTimeField(blank=True, help_text='When last weekly mix rank snapshot was taken', null=True),
        ),
    ]
