# Generated by Django 4.2.20 on 2025-11-02 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('transformers_2_0', '2.0 Transformers Products'), ('merges_1_0', '1.0 Merges & Figures')], default='transformers_2_0', max_length=20)),
                ('thumbnail', models.ImageField(upload_to='shop/thumbnails/')),
                ('main_image', models.ImageField(upload_to='shop/images/')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_active', models.BooleanField(default=False)),
                ('free_deadline', models.DateTimeField(blank=True, null=True)),
                ('free_deadline_active', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(help_text='URL where users will be redirected to purchase the product', max_length=500)),
                ('ecommerce_platform', models.CharField(choices=[('amazon', 'Amazon'), ('aliexpress', 'AliExpress'), ('ebay', 'eBay'), ('other', 'Other'), ('none', 'N/A')], default='none', help_text='Which e-commerce platform this product is from (only for 1.0 Merges & Figures)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
