# Generated by Django 4.2.20 on 2025-11-02 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Users who have favorited this product', related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
