# Generated by Django 4.2.20 on 2025-11-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL (YouTube/TikTok) for media gallery', null=True),
        ),
    ]
