# Generated by Django 4.2.20 on 2025-11-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Site Logo', help_text="Name/description for this logo (e.g., 'Main Logo', 'Channel Image')", max_length=200)),
                ('image', models.ImageField(help_text='Upload your main site logo/channel image', upload_to='site/logo/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one logo can be active at a time. Setting this to active will deactivate others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logos',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
