# Generated by Django 4.2.20 on 2025-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload your site favicon (recommended: .ico, .png, or .svg format, 32x32 or 16x16 pixels)', null=True, upload_to='site/favicon/'),
        ),
    ]
