# Generated by Django 4.2.20 on 2025-11-04 17:40

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image_2_product_image_3_product_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images/', validators=[shop.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images/', validators=[shop.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images/', validators=[shop.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='shop/images/', validators=[shop.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='shop/thumbnails/', validators=[shop.models.validate_image_file_size]),
        ),
    ]
