# Generated by Django 4.2.20 on 2025-07-02 15:22

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=announcements.models.upload_to)),
                ('image', models.ImageField(blank=True, null=True, upload_to=announcements.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
